### ISSUE TITLE
Release tag?

### ISSUE THREAD

**Issue by bfontaine** [jmoon018/PacVim#15]
Hi,
Could you please add a release tag on the repo? Something like e.g. `v1.0` or `v0.42.17` would be great. I’d like to write a formula to have PacVim in Homebrew, but they don’t accept HEAD-only programs (i.e. those without release tags) in the main repo.
Thanks

**Comment by jmoon018** [comment]
@bfontaine 

I just added a release tag. Let me know if that fixes your problem.

Thanks!

**Comment by bfontaine** [comment]
Yes it’s great, thanks!
