### ISSUE TITLE
Pacvim never loads a level I just see "YOU WIN THE GAME" when I hit enter

### ISSUE THREAD

**Issue by scottchiefbaker** [jmoon018/PacVim#28]
I just compiled `pacvim` on my Fedora 28 box and when I run it I see the menu:

     PRESS ENTER TO PLAY!
        ESC OR q TO EXIT!

When I hit enter I never see a level it just immediately says "YOU WIN THE GAME" and takes me to the next level. Am I doing something wrong?

**Comment by sidalit** [comment]
I had the same problem, use tag v1.1.0 `git checkout -b v1.1.0 v1.1.0`
and re-compile

**Comment by scottchiefbaker** [comment]
That fixed it thanks.
