### ISSUE TITLE
can't install in ubuntu 16.04

### ISSUE THREAD

**Issue by mapsic** [jmoon018/PacVim#37]
mapsic@Thinkpad:~/PacVim$ sudo make install
g++ -std=c++11 -DMAPS_LOCATION='"/usr/local/share/pacvim-maps"' -pthread   -c -o src/avatar.o src/avatar.cpp
In file included from src/avatar.h:27:0,
                 from src/avatar.cpp:19:
src/helperFns.h:24:21: fatal error: cursesw.h: 没有那个文件或目录
compilation terminated.
<builtin>: recipe for target 'src/avatar.o' failed
make: *** [src/avatar.o] Error 1

I got a error above.

**Comment by yehonathanlitman** [comment]
Just tried it and everything went OK. Before doing sudo make install do make.

**Comment by mapsic** [comment]
Thanks
