### ISSUE TITLE
curses.h or cursesw.h?What's the difference between them two?

### ISSUE THREAD

**Issue by ANCXY** [jmoon018/PacVim#42]
I install pacvim according to README.md, and get the errors followed:
src/helperFns.h:24:21: fatal error: cursesw.h: No such file or directory
src/globals.h:25:21: fatal error: cursesw.h: No such file or directory
So I try to edit the irc/helperFns.h and irc/globals.h,  where I changed it form `#include <cursesw.h>` to `#include <curses.h>` .
And it worked, but why?
Thanks!

**Comment by LIYAJUN2018** [comment]
you can sudo apt-get install libncurses5-dev
