### ISSUE TITLE
the wall can't be shown.

### ISSUE THREAD

**Issue by gaoxuezhan** [jmoon018/PacVim#44]
### the wall can't be shown.
<img width="234" alt="2018-12-02 3 53 37" src="https://user-images.githubusercontent.com/34319034/49337228-0f089180-f64b-11e8-8375-ba7995fdcea7.png">

**Comment by Zenexer** [comment]
You need to fix you TERM environment variable. This (probably) isn’t an issue with PacVim.

**Comment by fowlie** [comment]
I got the same problem on Ubuntu 18.04.3 LTS (Bionic Beaver). My TERM env is set to `xterm-256color`. Is that right or wrong?

**Comment by qiukuang** [comment]
I got the same problem on PUTTY.  Expand Window category, then select Translation. Check 'Enable VT100 line drawing even in UTF-8 mode' can fix it.
