### ISSUE TITLE
no known conversion for argument 1 from ‘Ghost1’ to ‘Ghost1&’

### ISSUE THREAD

**Issue by berezuev** [jmoon018/PacVim#7]
Hi. I've tried to install it on my debian wheezy, but I get the following error:

    g++ -w src/game.cpp -pthread -std=c++11 -lncurses src/globals.cpp src/helperFns.cpp src/avatar.cpp src/ghost1.cpp -o pacvim
    In file included from /usr/include/c++/4.7/bits/move.h:57:0,
                     from /usr/include/c++/4.7/bits/stl_pair.h:61,
                     from /usr/include/c++/4.7/bits/stl_algobase.h:65,
                     from /usr/include/c++/4.7/vector:61,
                     from src/game.cpp:7:
    /usr/include/c++/4.7/type_traits: In instantiation of ‘struct std::_Result_of_impl<false, false, std::_Mem_fn<void (Ghost1::*)(bool)>, Ghost1, bool>’:
    /usr/include/c++/4.7/type_traits:1857:12:   required from ‘class std::result_of<std::_Mem_fn<void (Ghost1::*)(bool)>(Ghost1, bool)>’
    /usr/include/c++/4.7/functional:1563:61:   required from ‘struct std::_Bind_simple<std::_Mem_fn<void (Ghost1::*)(bool)>(Ghost1, bool)>’
    /usr/include/c++/4.7/thread:133:9:   required from ‘std::thread::thread(_Callable&&, _Args&& ...) [with _Callable = void (Ghost1::*)(bool); _Args = {Ghost1&, bool}]’
    src/game.cpp:497:67:   required from here
    /usr/include/c++/4.7/type_traits:1834:9: error: no match for call to ‘(std::_Mem_fn<void (Ghost1::*)(bool)>) (Ghost1, bool)’
    In file included from /usr/include/c++/4.7/mutex:43:0,
                     from src/globals.h:5,
                     from src/game.cpp:10:
    /usr/include/c++/4.7/functional:525:11: note: candidates are:
    /usr/include/c++/4.7/functional:548:7: note: _Res std::_Mem_fn<_Res (_Class::*)(_ArgTypes ...)>::operator()(_Class&, _ArgTypes ...) const [with _Res = void; _Class = Ghost1; _ArgTypes = {bool}]
    /usr/include/c++/4.7/functional:548:7: note:   no known conversion for argument 1 from ‘Ghost1’ to ‘Ghost1&’
    /usr/include/c++/4.7/functional:553:7: note: _Res std::_Mem_fn<_Res (_Class::*)(_ArgTypes ...)>::operator()(_Class*, _ArgTypes ...) const [with _Res = void; _Class = Ghost1; _ArgTypes = {bool}]
    /usr/include/c++/4.7/functional:553:7: note:   no known conversion for argument 1 from ‘Ghost1’ to ‘Ghost1*’
    /usr/include/c++/4.7/functional:559:2: note: _Res std::_Mem_fn<_Res (_Class::*)(_ArgTypes ...)>::operator()(_Tp&, _ArgTypes ...) const [with _Tp = Ghost1; _Res = void; _Class = Ghost1; _ArgTypes = {bool}]
    /usr/include/c++/4.7/functional:559:2: note:   no known conversion for argument 1 from ‘Ghost1’ to ‘Ghost1&’
    make: *** [all] Error 1

What am I doing wrong?

**Comment by livibetter** [comment]
I have also noticed this issue for some time, waiting for a commit that PacVim would compile, but never came.

The message I got looked very similar to @berezuev's -- with latest 6db696d (2015-01-25) and 3da6cfb (2014-12-03), the first commit resulted similar messages -- except the files and line numbers, and C compiler version. Mine is GNU C Compiler is:`gcc (Gentoo 4.7.3-r1 p1.3, pie-0.5.5) 4.7.3`.

I don't know anything about C++, but I had suspected this might be compiler related, especially the versions, @berezuev used 4.7 and me 4.7.3, both 4.7.x.

I noticed that #13 discussed the GCC versions. So I really wonder if the message would be gone if I update to GCC 4.8. However, I truly don't want to do so, even 4.8.3 is the latest stable version in Gentoo Portage, 4.7.3 is the second next stable version.

If it's certain that GCC requires specific versions, presumably 4.8+, then it should be noted in `README`.

**Comment by jmoon018** [comment]
Truthfully, I am not sure what is causing the problem. I'd bet @livibetter is right, and that it's a compiler-related issue since you two are using 4.7.X. I'll try to do some research on it, but I can't guarantee anything. I will update the README soon to mention that gcc 4.8+ may be necessary

I'll leave the issue open. Any assistance is welcome, and it would also help if anyone could report the same bug (or report that PacVim works for gcc 4.7.x).

Sorry for the late response, and thanks for reporting @livibetter @berezuev

**Comment by berezuev** [comment]
@livibetter @jmoon018 I'll try to install gcc 4.8 today in the evening (utc+3) and then report about results.

**Comment by jmoon018** [comment]
@berezuev 

That would be awesome! Thanks.

**Comment by berezuev** [comment]
@jmoon018 i've some problems with gcc4.8 installing.
Just tried to start on gcc 4.9 and g++4.9. Works perfectly.

**Comment by jmoon018** [comment]
@berezuev 
Thanks for the update. Glad to know it's just a compiler issue. I'll add this to the README

But just to clarify, you tried PacVim on gcc 4.8, and PacVim didn't work, or you just couldn't install gcc 4.8 at all (for whatever reason)? I ask this because I'm currently using 4.8.2, and PacVim works -- I am wondering 4.8.x works for only some or all machines

**Comment by berezuev** [comment]
@jmoon018 
I just don't know, how to install gcc 4.8 on Wheezy i386 ))

**Comment by jmoon018** [comment]
@berezuev No problem, and thanks!

I was able to get it to work 4.8.x on OS X, so I assume 4.8.X will work for the other systems. Closing
